name: test syn
on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
    outputs:
      job_result_name: ${{ jobs.test.outputs.result_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result_name: ${{ steps.result_name.outputs.qwe }}
    steps:
      - name: SHow name
        id: result_name
        run: echo qwe=${{ inputs.name }}>> $GITHUB_OUTPUT